name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DOCKER_USERNAME
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.4.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Server address of Docker registry. If not set then will default to Docker Hub
        username: ${{ secrets.DOCKER_USERNAME }} # optional
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }} # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        # logout: # optional, default is true
    
    - name: Extract timestamp tag
      id: vars
      run: echo "TAG=$(date +%s)" >> "$GITHUB_OUTPUT"
    - name: Build the Docker image
      uses: docker/build-push-action@v6.16.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: . # optional
        # Path to the Dockerfile
        file: Dockerfile # optional
        
        push: true # optional, default is false
        
        tags: iosjkfivzn1231/live-server-docker:${{ steps.vars.outputs.TAG }} # optional

